version: "3.9"
services: 
    mq:
        image: "rabbitmq:alpine"
        ports: 
            - "5672:5672"
    web:
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            APP_ENVIRONMENT: prod
            MQ_CONNECTION_URL: amqp://mq:5672 
        depends_on:
            - mq