name: CD
 
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Dockerfile
        run: |
          touch Dockerfile
          cat >>./Dockerfile <<END
            FROM node:alpine
            WORKDIR app
            ENV APP_ENVIRONMENT=prod
            ENV MQ_CONNECTION_URL=$MQ_CONN
            COPY . .
            RUN npm install
            CMD ["npm", "start"]
          END
        env:
          MQ_CONN: ${{ secrets.MQ_CONNECTION_URL }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bw-statistics"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
